### ISSUE TITLE
data link is invalid

### ISSUE THREAD

**Issue by Li-Z-Q** [nguyentthong/CrossSummOptimalTransport#1]
I think this work is interesting and meaningful, so I want to run the code to learn detail things, but it seems that the data link https://drive.google.com/file/d/1bQ0gQuqGOdVf3QTx2WP7Gke1_bo0rtpz/view?usp=sharing is invalid. Could please author update this link? 

Thanks

**Comment by nguyentthong** [comment]
Sure, please wait until next week, I will provide a new data link.

**Comment by nguyentthong** [comment]
Hello, we have updated the link of data in the README file.

Regards

**Comment by Li-Z-Q** [comment]
I can open the data link now, thanks for your help 

Best wishes
