### ISSUE TITLE
Optimal Transport Distance for Knowledge Distillation

### ISSUE THREAD

**Issue by 526222883** [nguyentthong/CrossSummOptimalTransport#2]
I couldn't find the code implementation about the "Optimal Transport Distance for Knowledge Distillation". Could you please point me to where it is?

**Comment by nguyentthong** [comment]
Hi, 

Thank you for your interest in our work. You can look into the [loss.py (line 222)](https://github.com/nguyentthong/CrossSummOptimalTransport/blob/master/src/continual_NCLS/models/loss.py) file.

Regards,
Thong
